[build]
command = "ng build"
publish = "dist/billing-system"
functions = "netlify/functions"

[dev]
command = "ng serve"
targetPort = 4200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express"]
  node_bundler = "esbuild"
